### ISSUE TITLE
Review and edit CIE-10 codes for dropdown

### ISSUE THREAD

**Issue by rbwatson** [MercerU-TCO/CTS#97]
1. Review list of diseases and corresponding codes used in reports
2. Have Honduran students review the codes
3. Add codes to diagnosis fields.
4. Devise method to enter codes not in list.
5. Add DB table of codes/descriptions for reporting

**Comment by docsbydesign** [comment]
Fixed in codeLookup branch
(done)    Review list of diseases and corresponding codes used in reports
(done)    Have Honduran students review the codes (verified)
(done)    Add codes to diagnosis fields.--all codes supported using DB
(done)    Devise method to enter codes not in list. -- uncoded entries are highlighted
(done)    Add DB table of codes/descriptions for reporting
